### ISSUE TITLE
How to make it work on Taichi

### ISSUE THREAD

**Issue by theincognito-inc** [coderstory/CorePatch#1]
Hi,

Saw that part of the code was kanged from weishu. But weishu's corepatch only works till Android 9.
I tried yours and it works with Edxposed and android 10. But the same thing is not working with Taichi Magisk and Android 10. Any help would be appreciated. :)

**Comment by coderstory** [comment]
太极有专门的支持版本

**Comment by theincognito-inc** [comment]
谢谢
