### ISSUE TITLE
[BUG] Android R settings freeze

### ISSUE THREAD

**Issue by BlueMan1986** [coderstory/CorePatch#15]
**什么情况/What happened?**
Setting app of phone does not work on my Android 11 Mi 10T Pro phone. It just freeze.. When Core is enabled in edxposed.. 

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed: dont have it installed

Riru: v25.4.1.r411.22618... from magisk official...

**核心破解版本/Version of Core Patch?**
version: v3.4

**相关日志/Related Logs**
It is not worked when I updated to v3.4... Android settings app just freeze...
If I can help just tell me how...

**Comment by coderstory** [comment]
3.4 was add a function only。。。
Existing code is not modified

disable core and reboot will be ok？
