### ISSUE TITLE
[BUG] 模块在1+9R ColorOS11部分功能无效

### ISSUE THREAD

**Issue by Womsxd** [coderstory/CorePatch#18]
**什么情况/What happened?**

模块部分功能无效

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed:v1.4.5(5767)

Riru:v25.4.4.r246.05efc94

**核心破解版本/Version of Core Patch?**
version:3.5

**相关日志/Related Logs**
nologs

禁用模块和启用模块都无法直接降级安装应用(已检查过设置)，唯一的区别就是在[momo](https://www.coolapk.com/apk/io.github.vvb2060.mahoshojo)里开启后会系统服务异常，而关闭后无系统服务异常，以及签名错误可以直接安装

**Comment by Womsxd** [comment]
过签名校验正常工作

**Comment by coderstory** [comment]
color os 魔改的太多 不能用正常 而且我也没color os的机子 忽略

**Comment by Womsxd** [comment]
> color os 魔改的太多 不能用正常 而且我也没color os的机子 忽略

可以提供应用包管理程序的apk文件，替换系统的应用宝管理程序后全部都正常工作了

**Comment by jorismq** [comment]
> 

我是ONEPLUS9 PRO color os 11.2 android11，也是同样的问题。不能核心破解。有特殊处理的软件包安装程序吗？谢谢

**Comment by Womsxd** [comment]
> > 
> 
> 我是ONEPLUS9 PRO color os 11.2 android11，也是同样的问题。不能核心破解。有特殊处理的软件包安装程序吗？谢谢

可以考虑使用安装狮，我这边是用安装狮安装那些要降级的应用

**Comment by jorismq** [comment]
> 

是可以安装了。但是原来app的个人信息什么的没了。感觉只是把手动卸载和安装的过程简化了而已，并不是真正的“覆盖安装”
