### ISSUE TITLE
[BUG] 过不了v2验证

### ISSUE THREAD

**Issue by eebssk1** [coderstory/CorePatch#19]
**什么情况/What happened?**

如无法开机/模块无效等

**LSPosed及Riru版本/Version of LSPosed及Riru版本 and Riru**

LSPosed:1.4.7

Riru:25.4.4

**核心破解版本/Version of Core Patch?**
version:1.3.5

**相关日志/Related Logs**
no

using APK Signature Scheme v2. Failed to parse/verify signer #1 block: SHA256withRSA signature did not verify

**Comment by eebssk1** [comment]
ArrowOS(Fully AOSP based)11

**Comment by eebssk1** [comment]
看起来没有成功强行v1

**Comment by coderstory** [comment]
你已修复
