### ISSUE TITLE
doesn't work on huawei mediapad m5 lite (bah2-w19) tablet (oreo)

### ISSUE THREAD

**Issue by patrickdrd** [coderstory/CorePatch#3]
I'm trying to make it work on my huawei mediapad m5 lite (bah2-w19) tablet (oreo),
can you help?

I'm attaching xposed log

thanks

[xposed_error_20200611_201654.log](https://github.com/coderstory/CorePatch/files/4769092/xposed_error_20200611_201654.log)

**Comment by coderstory** [comment]
branch master -> support android 4.4-7.x
branch Q -> support android 9.0-10.0

**no android 8.0**
